name:                FakeReviewDetector
version:             0.1.0.0
github:              "artik008/FakeReviewDetector"
license:             BSD3
author:              "Artyom Shitik"
maintainer:          "artik008@yandex.ru"
copyright:           "2019 Shitik Artyom"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/artik008/FakeReviewDetector#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- curl
- directory
- pretty-show
- strict
- string-conversions
- tagsoup
- text
- time
- turtle
default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  FakeReviewDetector-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FakeReviewDetector

tests:
  FakeReviewDetector-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FakeReviewDetector
